### ISSUE TITLE
Making it middleware and using macros.

### ISSUE THREAD

**Issue by f** [Thyra/kemal-session#1]
This is a very nice idea! And Kemal absolutely needs an elegant session management.

I am forked this and started development of making it easier to use!

I will make it a middleware for Kemal and I will write some macros to use it like filters. My proposal is something like that:

```crystal
use_sessions # the macro

get "/" do |env|
  env.session.int["random_key"] # middleware will push sessions to env.
end
```

**Comment by f** [comment]
And WDYT @sdogruyol?

**Comment by Thyra** [comment]
Hi! That's a great idea! Thanks a lot!

**Comment by sdogruyol** [comment]
Definitely a great way to add sessions `use_sessions` :+1:
