### ISSUE TITLE
`sessions_dir` is about filesystem engine and shouldn't be in general

### ISSUE THREAD

**Issue by f** [Thyra/kemal-session#5]
I am digging your codebase, and I saw you use `sessions_dir` configuration. But it is about `filesystem` engine. If I am using Redis, I won't use `sessions_dir`.

And engines are hardly coupled to the codebase. If I write a shard that uses redis, I should open a PR to your codebase to add the engine to support it as far as I read your code. The engines should work as middlewares.

We need a simple `Engine` abstraction stg. like that:

```crystal
module Session
  abstract class Engine
    def read(key : String)
    end

    def write(key : String, value : String)
    end

    def delete(key : String)
    end

    def on_timeout
    end

    def to_s

    end
  end
end
```

And we should extend our engines:

```crystal
class FileSystemEngine < Session::Engine
    initialize(config)
        @sessions_dir = ...
    end
    read(key : String)
        # How to read from file
    end
    # ...
end
```

WDYT about this abstraction?

**Comment by Thyra** [comment]
Yes, I agree and I think its a good idea. So an abstract Engine class could look like this:
```crystal
abstract class Engine

  abstract def save
  abstract def self.restore_instance
  abstract def self.gc

end
```
In my concept so far the engine doesn't handle the actual values itself, they are always stored in hashes directly in the Session, it just takes care of saving/restoring the session to the filesystem, database etc. This way you don't need to read and parse a json file each time the user wants to retrieve a value, for example. You just do it once when initializing the session. And the garbage collection of course is dependant on the engine as well, so the abstract engine needs to contain that, too.

But if you remove the ```sessions_dir``` from the config, how does the user set the directory the sessions are saved in? I don't want him to have to deal with all the internals like ```Session.Engines::FileSystemEngine.config.sessions_dir = "foobar"``` or something like that...

**Comment by Thyra** [comment]
On the other hand, the Engine could take care of when it reads and writes files itself, for example read all the values into a hash the initialize method and when ``Engine.read``` is called just look it up in the hash but then we would have to delegate ``session.int`` method etc. to the engine as well... Hm, yes, I think this should work. Than the engine needs to provide read, write and delete operations for each data type though.

**Comment by Thyra** [comment]
Ah, I got it: 
```crystal
Session.config.engine("filesystem", { sessions_dir: "foo", another_option: "bar" })
```

**Comment by Thyra** [comment]
So here is a first draft:
```crystal
abstract class Engine
  abstract def initialize(options : Hash(Symbol, String))
  abstract def run_gc

  abstract def int(key : String, value : Int32)
  abstract def int(key : String, value : Nil) # for deleting values
  abstract def int(key : String) : Int32
  abstract def int?(key : String) : Int32?
  #... the same for all other data types (use a macro for that)
end
```
Is that how you meant it?

**Comment by f** [comment]
Wow I liked your abstraction. That's exactly what I meant. Simply decoupling engines and make them plug'n'play things. So I can build another library stg. like `kemal-session-redis` as a simple Engine that requires your library.

**Comment by Thyra** [comment]
Okay, I did it. Take a look at the _abstract_engines_ branch. I wrote a DummyEngine as well. If you execute the _dummy_example.cr_ this is the output (without Kemal logs):
```
Initalizing DummyEngine with these options: {:option => "Valuw"}
#<Session::DummyEngine:0x165efd0>
Initalizing DummyEngine with these options: {:option2 => "value2"}
#<Session::DummyEngine:0x165efc0>
Running gc
```
Then if you open the browser to ``/``
```
Session 2d7e875722d9fb115a920f640688eeeb: Maybe getting value of sas
Session 2d7e875722d9fb115a920f640688eeeb: Setting value of hu to ha
Session 2d7e875722d9fb115a920f640688eeeb: Getting Hash of Float64
```
So now it will be easy to create clean plug'n'play engines :-)

**Comment by f** [comment]
Wow you made a huge work! :+1: @sdogruyol you should see that.

**Comment by Thyra** [comment]
I merged it into the development branch. So from now on this is the new official engine system ;-).
