### ISSUE TITLE
declaring the type of a local variable is not yet supported

### ISSUE THREAD

**Issue by solisoft** [Thyra/kemal-session#7]
I'm trying your sample script within crystal 0.15 but it raise this error : 

Error in ./src/app.cr:11: instantiating 'Session:Class#start(HTTP::Server::Context)'

  session = Session.start(env)
                    ^~~~~

in ./libs/kemal-session/kemal-session/base.cr:41: declaring the type of a local variable is not yet supported

  def self.start(context) : Session
    ^~~~~~~~

Here my script : 

    require "secure_random"
    require "redis"
    require "kemal"
    require "kemal-session"
    
    # Home page 
    get "/" do |env|
      session = Session.start(env)
      # session.string("uuid", SecureRandom.uuid)
      name = session.inspect
      render "src/views/home/index.html.ecr", "src/views/layouts/layout.html.ecr"
    end

**Comment by Thyra** [comment]
Sorry for not answering – I wasn't really active here during the last weeks and didn't notice you opened an issue. Anyway, it's fixed now, thank you for reporting the bug!
